(BSR)[API] bump: Bump Werkzeug
Changelog: https://werkzeug.palletsprojects.com/en/2.2.x/changes/

Required changes:

- We cannot write in `flask._app_ctx_stack` anymore. Setting (yes,
  *setting*, not getting) a value raises an error:

      AttributeError: 'LocalStack' object has no attribute '_query_logger'

  Other Flask-based projects (including Flask-SQLAlchemy [1]) now use
  `flask.g` instead. We'll do the same.

- Calling `request.get_json()` now raises a `BadRequest` exception if
  the `Content-Type` header is not `application/json`. But that's not
  a problem if the body is empty.

  See pallets/werkzeug@6f7e1e57462b63bde7a992048c6d56f5ef for the change.

[1] https://github.com/pallets-eco/flask-sqlalchemy/commit/580d75b202a4d0e837fedc7c2dd45db9044e1513