(BSR)[API] feat: Require body (payload) in our `@task` decorator
We're going to add typing annotations, and having an optional body
(with an annotation like `body: pydantic.BaseModel | None`) raises an
error in Spectree:

      File "src/pcapi/tasks/decorator.py", line 68, in _define_handler
        def handle_task(body: pydantic_v1.BaseModel | None = None) -> None:
      File "src/pcapi/serialization/decorator.py", line 136, in decorate_validation
        def sync_validate(*args: Any, **kwargs: Any) -> Response:
      File "env/pcapi/lib/python3.10/site-packages/spectree/spec.py", line 235, in decorate_validation
        model_key = self._add_model(model=model)
      File "src/pcapi/serialization/spec_tree.py", line 56, in _add_model
        model_key = get_model_key(model=model)
      File "src/pcapi/serialization/spec_tree.py", line 15, in get_model_key
        return model.__name__
    AttributeError: 'types.UnionType' object has no attribute '__name__'. Did you mean: '__ne__'?

So let's declare that all tasks must receive a payload. This is fine:
it is already the case.