(PC-18236)[API] fix: backoffice: validation error for OffererToBeValidated
ValidationError: 1 validation error for OffererToBeValidated
address
  none is not an allowed value (type=type_error.none.not_allowed)

Actually adress is nullable un HasAddressMixin so it can be null in
database

(cherry picked from commit c6aeb5dd7c087595d8a3230cb41b4e35367e45d0)