(PC-35943)[API] fix: circular import in celery tasks
pc-celery-worker    | Error:
pc-celery-worker    | Unable to load celery application.
pc-celery-worker    | While trying to load the module pcapi.celery_tasks.celery_worker the following error occurred:
pc-celery-worker    | Traceback (most recent call last):
pc-celery-worker    |   File "/home/pcapi/.local/lib/python3.11/site-packages/celery/app/utils.py", line 383, in find_app
pc-celery-worker    |     sym = symbol_by_name(app, imp=imp)
pc-celery-worker    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pc-celery-worker    |   File "/home/pcapi/.local/lib/python3.11/site-packages/kombu/utils/imports.py", line 64, in symbol_by_name
pc-celery-worker    |     return getattr(module, cls_name) if cls_name else module
pc-celery-worker    |            ^^^^^^^^^^^^^^^^^^^^^^^^^
pc-celery-worker    | AttributeError: module 'pcapi.celery_tasks' has no attribute 'celery_worker'
pc-celery-worker    |
pc-celery-worker    | During handling of the above exception, another exception occurred:
pc-celery-worker    |
pc-celery-worker    | Traceback (most recent call last):
pc-celery-worker    |   File "/home/pcapi/.local/lib/python3.11/site-packages/celery/bin/celery.py", line 141, in celery
pc-celery-worker    |     app = find_app(app)
pc-celery-worker    |           ^^^^^^^^^^^^^
pc-celery-worker    |   File "/home/pcapi/.local/lib/python3.11/site-packages/celery/app/utils.py", line 386, in find_app
pc-celery-worker    |     sym = imp(app)
pc-celery-worker    |           ^^^^^^^^
pc-celery-worker    |   File "/home/pcapi/.local/lib/python3.11/site-packages/celery/utils/imports.py", line 109, in import_from_cwd
pc-celery-worker    |     return imp(module, package=package)
pc-celery-worker    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pc-celery-worker    |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
pc-celery-worker    |     return _bootstrap._gcd_import(name[level:], package, level)
pc-celery-worker    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pc-celery-worker    |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
pc-celery-worker    |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
pc-celery-worker    |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
pc-celery-worker    |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
pc-celery-worker    |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
pc-celery-worker    |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
pc-celery-worker    |   File "/usr/src/app/src/pcapi/celery_tasks/celery_worker.py", line 1, in <module>
pc-celery-worker    |     from pcapi.celery_tasks import sendinblue  # noqa: F401
pc-celery-worker    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pc-celery-worker    |   File "/usr/src/app/src/pcapi/celery_tasks/sendinblue.py", line 4, in <module>
pc-celery-worker    |     from pcapi.core.external import sendinblue
pc-celery-worker    |   File "/usr/src/app/src/pcapi/core/external/sendinblue.py", line 19, in <module>
pc-celery-worker    |     from pcapi.celery_tasks.sendinblue import update_contact_attributes_task_celery
pc-celery-worker    | ImportError: cannot import name 'update_contact_attributes_task_celery' from partially initialized module 'pcapi.celery_tasks.sendinblue' (most likely due to a circular import) (/usr/src/app/src/pcapi/celery_tasks/sendinblue.py)