(BSR)[API] chore: Add typing annotation for `@task` decorator
I did not find any solution to properly annotate the `handle_task`
inner function. mypy reports:

    error: Variable "payload_type" is not valid as a type  [valid-type]

So we're left with a "type: ignore".