(PC-40953)[API] fix: VenueContactModelV2.website blocks everything
The recent VenueContactModelV2.website update added a mix of
HttpUrl/UrlConstraints and an url validation regex. These do not work
together:

TypeError: Unable to apply constraint 'pattern' to supplied value
https://passculture.app for schema of type 'function-wrap'

This commit should:

1. fix this issue
2. with the same expected validation since the URL regex should do the
   same job as the HttpUrl and UrlConstraints.host_required parts.