(PC-10438) payments: Remove overlapping exclusion constraint on custom rules
tl;dr: the constraint must be updated, but I cannot find a way to do
that. So I remove it, and we will add validation in Python. That
should be good enough.

That constraint worked well when custom reimbursement rules could only
be related to offers. Now that a rule may be related to an offer or an
offerer (and possibly categories), this constraint should be updated:
we should not allow 2 rules with the same offerer, overlapping
timespan and overlapping categories.

I tried to add a new constraint like this:

    ALTER TABLE custom_reimbursement_rule
    ADD CONSTRAINT custom_reimbursement_rule_overlapping_excl
    EXCLUDE USING gist (
        "offerId" WITH =,
        "offererId" WITH =,
        categories WITH &&,
        timespan WITH &&
    );

But the part on the `categories` column fails:

    ERROR:  data type text[] has no default operator class for access method "gist"
    HINT:  You must specify an operator class for the index or define a default operator class for the data type.

I cannot find a way around. There seems to be a third-party extension
called `smlar` that would help, but even if we could install it on our
Google Cloud Platform database (which does not seem to be possible),
that would make the setup more complex than needed.

It's more simple to remove the constraint, and rely on a Python-based
validation, which will be added later.