(BSR)[API] test: Fix bytes/string confusion in `css_font_http_request_mock`
The real response object returns bytes, not text. This caused
a (benign) warning when running tests:

    ERROR [weasyprint] Failed to load stylesheet at [...]:
    TypeError: a bytes-like object is required, not 'str'