(BSR)[API] bump(sqla1.4): use Model.registry instead of Model._decl_class_registry
fix AttributeError: 'type object 'Model' has no attribute '_decl_class_registry'' - see this issue and comment: https://github.com/sqlalchemy/sqlalchemy/issues/6080\#issuecomment-801223491