(BSR)[API] test: Add conditional autouse fixture to detect data leaks in tests
If a test adds data in the database without using the `db_session` (or
the `clean_database`) fixture, other tests will fail because they do
not expect this additional data.

Now we can set an environment variable so that `pytest` counts the
number of instances of the requested models before and after each
test, and reports leaks.

Example:

    CHECK_DATA_LEAKS=pcapi.core.offers.models.Offer pytest

The environment variable accepts a comma-separated list of model
paths.

The output looks like:

    tests/foo/tests.py::some_bogus_test PASSED
    tests/foo/tests.py::some_bogus_test ERROR

    [...]
    tests/conftest.py:262: in check_data_leaks
        assert not leaked_models, f"LEAK: {request.function} leaks {leaked_models}"
    E   AssertionError: LEAK: <bound method OfferCriterionTest.test_unique_offer_criterion of <tests.core.criteria.test_models.OfferCriterionTest object at 0x7f80c4eda170>> leaks Offer, Product
    E   assert not 'Offer, Product'