(BSR)[API] feat: Simplify signature of rate limiting utility functions
Recent versions of Flask-Limiter have strict typing annotations. Our
"kwargs" arguments caused a wall of mypy warnings for _each_ argument
of _each_ call. For example, for just _one_ call:

    rate_limiting.py:73:67: error: Argument 2 to "shared_limit" of "Limiter" has incompatible type "**dict[str, object]"; expected "str | Callable[[str], str]"  [arg-type]
    rate_limiting.py:73:67: error: Argument 2 to "shared_limit" of "Limiter" has incompatible type "**dict[str, object]"; expected "Callable[[], str] | None"  [arg-type]
    rate_limiting.py:73:67: error: Argument 2 to "shared_limit" of "Limiter" has incompatible type "**dict[str, object]"; expected "bool"  [arg-type]
    rate_limiting.py:73:67: error: Argument 2 to "shared_limit" of "Limiter" has incompatible type "**dict[str, object]"; expected "list[str] | None"  [arg-type]
    rate_limiting.py:73:67: error: Argument 2 to "shared_limit" of "Limiter" has incompatible type "**dict[str, object]"; expected "str | None"  [arg-type]
    rate_limiting.py:73:67: error: Argument 2 to "shared_limit" of "Limiter" has incompatible type "**dict[str, object]"; expected "Callable[[], bool] | None"  [arg-type]
    rate_limiting.py:73:67: error: Argument 2 to "shared_limit" of "Limiter" has incompatible type "**dict[str, object]"; expected "Callable[[Response], bool] | None"  [arg-type]
    rate_limiting.py:73:67: error: Argument 2 to "shared_limit" of "Limiter" has incompatible type "**dict[str, object]"; expected "Callable[[RequestLimit], Response | None] | None"  [arg-type]
    rate_limiting.py:73:67: error: Argument 2 to "shared_limit" of "Limiter" has incompatible type "**dict[str, object]"; expected "int | Callable[[], int]"  [arg-type]

We could use a TypedDict. I tried but could not remove all warnings.
And the code was much less readable.

The solution is to remove all "kwargs", which we almost never use.

Also, we slightly change `get_basic_auth_from_request` so that it
always returns a string, which is what Flask-Limiter requires. There
is no change in the behaviour, since we use `exempt_when` if the user
is not logged in.