(PC-35941)[API] fix: (upgrade to sqlalchemy 2) sqlalchemy.orm.exc.MappedAnnotationError
Co-authored-by: Vencespass <113904392+vroullier-pass@users.noreply.github.com>

Fixes exceptions while starting backend or running sandbox, related to
annotations:

- sqlalchemy.orm.exc.MappedAnnotationError: Type annotation for "Chronicle.user" can't be correctly interpreted for Annotated Declarative Table form.  ORM annotations should normally make use of the ``Mapped[]`` generic type, or other ORM-compatible generic type, as a container for the actual type, which indicates the intent that the attribute is mapped. Class variables that are not intended to be mapped by the ORM should use ClassVar[].  To allow Annotated Declarative to disregard legacy annotations which don't use Mapped[] to pass, set "__allow_unmapped__ = True" on the class or a superclass this class. (Background on this error at: https://sqlalche.me/e/20/zlpr)

- AttributeError: 'list' object has no attribute '_sa_instance_state'

- sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) null value in column "priceCategoryLabelId" of relation "price_category" violates not-null constraint